bullseye has been EOL
```
Status: Downloaded newer image for debian:bullseye
Get:1 http://deb.debian.org/debian bullseye InRelease [75.1 kB]
Get:2 http://deb.debian.org/debian-security bullseye-security InRelease [27.2 kB]
Get:3 http://deb.debian.org/debian bullseye-updates InRelease [44.0 kB]
Get:4 http://deb.debian.org/debian bullseye/main amd64 Packages [8066 kB]
Get:5 http://deb.debian.org/debian bullseye-updates/main amd64 Packages [18.8 kB]
Reading package lists...
E: Release file for http://deb.debian.org/debian-security/dists/bullseye-security/InRelease is expired (invalid since 3d 16h 42min 19s). Updates for this repository will not be applied.
Error: Process completed with exit code 100.
```

Close #84